---
:date: '2014-03-27 01:09:02 -0700'
:pricing:
  :g3-standard-0.625-smartos: 0.02
  :g3-standard-1.75-smartos: 0.056
  :g3-standard-3.75-smartos: 0.12
  :g3-standard-7.5-smartos: 0.24
  :g3-standard-15-smartos: 0.48
  :g3-standard-30-smartos: 0.96
  :g3-standard-48-smartos: 1.536
  :g3-standard-64-smartos: 2.048
  :g3-standard-80-smartos: 2.56
  :g3-standard-96-smartos: 3.072
  :g3-standard-128-smartos-cc: 4.096
  :g3-highmemory-17.125-smartos: 0.409
  :g3-highmemory-34.25-smartos: 0.817
  :g3-highmemory-68.375-smartos: 1.63
  :g3-highmemory-144-smartos: 3.433
  :g3-highmemory-256-smartos-cc: 6.102
  :g3-highcpu-1.75-smartos: 0.127
  :g3-highcpu-7-smartos: 0.508
  :g3-highcpu-16-smartos: 1.16
  :g3-highcpu-24-smartos: 1.739
  :g3-highcpu-32-smartos-cc: 2.319
  :g3-highio-15-smartos: 0.76
  :g3-highio-30-smartos: 1.52
  :g3-highio-60.5-smartos: 3.067
  :g3-highio-128-smartos: 6.488
  :g3-highio-256-smartos-cc: 12.976
  :g3-highstorage-32-smartos: 0.863
  :g3-highstorage-64-smartos: 1.726
  :g3-highstorage-128-smartos-cc: 3.451
  :g3-standard-0.625-kvm: 0.02
  :g3-standard-1.75-kvm: 0.056
  :g3-standard-3.75-kvm: 0.12
  :g3-standard-7.5-kvm: 0.24
  :g3-standard-15-kvm: 0.48
  :g3-standard-30-kvm: 0.96
  :g3-highmemory-17.125-kvm: 0.409
  :g3-highmemory-34.25-kvm: 0.817
  :g3-highmemory-68.375-kvm: 1.63
  :g3-highcpu-1.75-kvm: 0.127
  :g3-highcpu-7-kvm: 0.508
  :g3-highio-15-kvm: 0.76
  :g3-highio-30-kvm: 1.52
  :g3-highio-60.5-kvm: 3.067
  :g3-highstorage-32-kvm: 0.863
